### ISSUE TITLE
Error: Command failed: truffle test at checkExecSyncError (child_process.js:592:13)

### ISSUE THREAD

**Issue by JohnAllen** [gnosis/run-with-testrpc#3]
{ Error: Command failed: truffle test
    at checkExecSyncError (child_process.js:592:13)
    at execSync (child_process.js:632:13)
    at Promise.then (/Users/john/contracts/node_modules/run-with-testrpc/bin/run-with-testrpc.js:49:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  error: null,
  cmd: 'truffle test',

...

Failed to exec test script
13 verbose stack Error: distense-contracts@0.1.0 test: `run-with-testrpc 'truffle test'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)

Anyone run into this one?

**Comment by JohnAllen** [comment]
BTW, the tests run.  This happens after all of them have run

**Comment by cag** [comment]
Man that is weird. May I get the OS/node version?

**Comment by cag** [comment]
Actually, maybe it's because the tests failed? I'll have to double check on some repos I have access to, but that may be expected...

**Comment by JohnAllen** [comment]
Mac Sierra latest 
Node v8.7.0

Will run a single passing test and see what happens

**Comment by JohnAllen** [comment]
Hmm, you were right.  When no tests fail it doesn't throw all of that.  Wondering if there's a way to prevent that while in development mode though.  Thanks for feedback -- let me know if you have any suggestions -- closing.

**Comment by cag** [comment]
@JohnAllen The error is based on the exit code. In the interest of not letting errors pass, I have preserved the error from execSync, but maybe it would be better to handle that error specifically...

In any case,  you can squash the error for development by making the exit code indicate passing tests: `run-with-testrpc 'truffle test || exit 0'`.

**Comment by cag** [comment]
Dunno if anybody is paying attention to this issue still, but in the interest of not encouraging bad practices and telling people to squash errors, I've made the error handling prettier and less noisy in v0.3.0

So yeah @JohnAllen sorry for the bad advice ;)
